[package]
name = "jackal"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort'
strip = true
lto = 'fat'
codegen-units = 1
opt-level = 3

[dependencies]
colored = "*"
once_cell = "1.10.0"
console = "0.15"
bytemuck = "1.18.0"
rand = "0.8.5"
crossbeam-queue = "0.3.11"